peer-network/peer_backend

.github/workflows/deploy.yml, autopull.txt
the changes on dev are pushed to main to check out if automation is working now.
=> merging dev into main

sql_files_for_import/structure.psql
we worked on the backend server for quite some time these are all the changes.
=> Initial merge of the current backend into development

composer.json
=> composer upload

composer.json
=> Merge development into main

src/admin_schema.graphl, src/schema.graphl
set resolvers for userinfo, postinfo, commentinfo
=> schema update

src/GraphQLSchemaBuilder.php, src/admin_schema.graphl, src/schema.graphl
=> Builder changes

src/GraphQLSchemaBuilder.php, src/admin_schema.graphl, src/schema.graphl
=> UPDATE SCHEMA; BUILDER

src/Database/PostMapper.php, src/admin_schema.graphl, src/schema.graphl
Update getallposts to handle search of postId, userId
=> Add New Function into getallposts to handle search by userId, postId

src/App/UserService.php
update user service -image -biography
=> update user service to img, biography to not be null

src/App/UserService.php
=> update user service tabs to spaces

src/App/ChatService.php, src/Database/ChatMapper.php, src/Database/CommentInfoMapper.php, src/Database/CommentMapper.php, src/Database/ContactusMapper.php, src/Database/DailyFreeMapper.php, src/Database/McapMapper.php, src/Database/NewsFeedMapper.php, src/Database/PostInfoMapper.php, src/Database/PostMapper.php, src/Database/Rechnen.php, src/Database/TagMapper.php, src/Database/UserInfoMapper.php, src/Database/UserMapper.php, src/Filter/PeerInputFilter.php, src/Handler/GraphQLHandler.php, src/RateLimiter/RateLimiter.php, src/config/checker.php, src/config/dependencies.php, src/config/settings.php
Replace Tabs to Spaces in src / Database
=> Tabs to Spaces

README.md
After the big changes in the last merge we forgot to update the ReadMe file..
=> docs(ReadMe): Add one composer dependecy to the ReadMe setup guide

composer.json
remove uneeded repos from composer.js file
=> remove uneeded repo from composer.js

sql_files_for_import/structure.psql
convert tab to space, add more functions and improve many classes
=> convert tab to space, add more functions and improve many classes

src/GraphQLSchemaBuilder.php, src/admin_schema.graphl, src/schema.graphl
=> improve it

src/config/checker.php, src/config/dependencies.php, src/config/middleware.php, src/config/routes.php, src/config/settings.php
=> improve config

src/Services/Base64FileHandler.php, src/Services/FileUploadDispatcher.php, src/Services/ImageChatService.php, src/Services/ImagePostService.php, src/Services/JWTService.php, src/Services/NotesPostService.php, src/Services/PodcastPostService.php, src/Services/UserAvatarService.php, src/Services/UserBiographyService.php, src/Services/VideoPostService.php
=> improve services classes

src/Middleware/RateLimiterMiddleware.php, src/Middleware/SecurityHeadersMiddleware.php
=> improve middleware

src/RateLimiter/RateLimiter.php
=> improve rate limiter

src/Handler/GraphQLHandler.php, src/Handler/NotFoundHandler.php
=> improve handler classess

src/Database/ChatMapper.php, src/Database/CommentInfoMapper.php, src/Database/CommentMapper.php, src/Database/ContactusMapper.php, src/Database/DailyFreeMapper.php, src/Database/McapMapper.php, src/Database/NewsFeedMapper.php, src/Database/PoolMapper.php, src/Database/PostInfoMapper.php, src/Database/PostMapper.php, src/Database/Rechnen.php, src/Database/TagMapper.php, src/Database/TagPostMapper.php, src/Database/UserInfoMapper.php, src/Database/UserMapper.php, src/Database/WalletMapper.php
=> improve database classess

src/BaseURL.php
=> improve baseurl

src/App/PostAdvanced.php
=> fix validate user array

src/GraphQLSchemaBuilder.php, src/admin_schema.graphl
=> Refactor: Updated GraphQLSchemaBuilder and admin_schema.graphl

src/GraphQLSchemaBuilder.php
=> improve schemaBuilder

src/GraphQLSchemaBuilder.php
improve schema Builder resolveCooments.ResponseCode
=> improve resolveComments ResponseCode

sql_files_for_import/structure.psql, src/App/PostAdvanced.php, src/App/PostMedia.php, src/App/PostService.php, src/Database/PostMapper.php, src/GraphQLSchemaBuilder.php, src/Services/Base64FileHandler.php, src/Services/CoverPostService.php, src/Services/FileUploadDispatcher.php, src/Services/ImageChatService.php, src/Services/ImagePostService.php, src/Services/NotesPostService.php, src/Services/PodcastPostService.php, src/Services/UserAvatarService.php, src/Services/VideoPostService.php, src/admin_schema.graphl, src/schema.graphl
update sql: add posts_media for next to accept all media link inside.
update MediaHandler And Uploading Media files.
update PostMapper to insert Media data to PostMedia.
Clean SchemaBuilder from unused functions and uses.
Add a CoverClass.
update VideClass, AudioClass, TextClass, ImageClass.
Add FileUploadDisPatcher.
Add PostsMedia Validator.
=> update sql table, PostServices, SchemaBuilder, MediaHandler

src/App/ChatService.php, src/App/WalletService.php, src/Database/WalletMapper.php, src/GraphQLSchemaBuilder.php, src/RateLimiter/RateLimiter.php, src/admin_schema.graphl, src/schema.graphl
update graphql schema, rate limiter, chatservices to save the chat banner to chat media folder and .....
=> T ras/updaterepo2

sql_files_for_import/structure.psql, src/App/CommentService.php, src/App/Commented.php, src/App/McapService.php, src/App/PoolService.php, src/App/PostInfoService.php, src/App/ProfilUser.php, src/App/Profile.php, src/App/User.php, src/App/UserAdvanced.php, src/App/UserInfo.php, src/App/UserService.php, src/App/WalletService.php, src/Bench/Bench.php, src/Database/ChatMapper.php, src/Database/CommentMapper.php, src/Database/PoolMapper.php, src/Database/PostMapper.php, src/Database/UserInfoMapper.php, src/Database/UserMapper.php, src/Database/WalletMapper.php, src/GraphQLSchemaBuilder.php, src/admin_schema.graphl, src/bridge_schema.graphl, src/schema.graphl, src/schemaguest.graphl
update and remove many function for the next update.
=> Upload new update

src/App/UserInfoService.php
=> clean userservices

src/App/ChatService.php, src/App/UserInfoService.php, src/Database/ChatMapper.php, src/Database/UserInfoMapper.php, src/Database/WalletMapper.php, src/GraphQLSchemaBuilder.php, src/admin_schema.graphl, src/schema.graphl
=> limit offset validation

src/GraphQLSchemaBuilder.php, src/admin_schema.graphl, src/schema.graphl
=> blocklist counter

src/schemaguest.graphl
Add public key fix by registering a new account.
=> pub key fixed

composer.json, src/App/ChatService.php, src/App/PoolService.php, src/App/PostService.php, src/App/WalletService.php, src/Database/ChatMapper.php, src/Database/PoolMapper.php, src/Database/PostMapper.php, src/Database/WalletMapper.php, src/GraphQLSchemaBuilder.php
improve code for php 8.3.19 compatible
=> improve code for php 8.3.19 compatible

src/Database/DailyFreeMapper.php
Again fix date change for dailyfree
=> fix date change for dailyfree 2

src/App/Chat.php, src/App/ChatService.php, src/App/CommentAdvanced.php, src/App/CommentService.php, src/App/PostMedia.php, src/App/PostService.php, src/Database/ChatMapper.php, src/Database/CommentMapper.php, src/Database/UserInfoMapper.php, src/Filter/PeerInputFilter.php, src/GraphQLSchemaBuilder.php, src/admin_schema.graphl, src/schema.graphl
fix parentid comments, readMessages, .....
Add amountreplies, 1 to 1 chats will disbaled by unfollow some, enabled by refollows, .......
=> fix and add some functions in some classess: chats, follows, comments

sql_files_for_import/structure.psql, src/App/ChatService.php, src/App/CommentService.php, src/App/ContactusService.php, src/App/PostInfoService.php, src/App/PostService.php, src/Database/ChatMapper.php, src/Database/ContactusMapper.php, src/Database/PostInfoMapper.php, src/Database/PostMapper.php, src/Database/UserInfoMapper.php, src/Database/UserMapper.php, src/GraphQLSchemaBuilder.php, src/admin_schema.graphl, src/bridge_schema.graphl, src/config/settings.php, src/schema.graphl, src/schemaguest.graphl
General Update, Schema, Validations nd more
=> General Update for schema, validations, and some classess

src/Filter/PeerInputFilter.php, src/GraphQLSchemaBuilder.php, src/Utils/ResponseHelper.php, src/config/checker.php
turn response code to integer.
=> response code to int

src/App/ChatService.php
Change response code from str to int.
=> I change all response code from str to int

src/Filter/PeerInputFilter.php
continue updating responsecode (PeerFilter)
=> Continue updating responsecode

src/App/CommentInfoService.php, src/App/CommentService.php, src/App/PostInfoService.php, src/App/PostService.php
Clickup: [86c2xx0m4](https://app.clickup.com/t/86c2xx0m4)
=> added ResponseCodes to CommentInfoService, CommentService, PostInfoService, PostService

src/App/WalletService.php, src/Database/WalletMapper.php
Change multiple response code according to provided information.
Affected files:
`src/App/WalletService.php`
`src/Database/WalletMapper.php`
=> feat(response code): update response code on WalletService, WalletMapper

src/Filter/PeerInputFilter.php
=> tabspaces inputfilter

src/App/TagPostService.php, src/App/TagService.php
Clickup:[86c2xx0m4](https://app.clickup.com/t/86c2xx0m4)
=> added ResponseCodes to TagPostService, TagService

src/Filter/PeerInputFilter.php, src/GraphQLSchemaBuilder.php
=> continue responsecode updates

src/Filter/PeerInputFilter.php
change response code for image
=> input filter

src/App/ContactusService.php, src/Database/WalletMapper.php
Change multiple response code according to provided information.
Affected files:
`src/App/ContactusService.php`
`src/Database/WalletMapper.php`
=> feat(response code): update response code on contactusservice walletmapper

src/App/ChatService.php, src/App/McapService.php, src/App/TagPostService.php
Changed response codes from string to integer in ChatService, TagService, TagPostService, and McapService.
=> Changed response codes:Chat, Tag, TagPost and Mcap services

src/App/PostService.php, src/App/UserService.php, src/Database/ChatMapper.php, src/Database/McapMapper.php
ClickUp: [86c2xx0m4](https://app.clickup.com/t/86c2xx0m4)
=> fix(codes): change some generic 40301 responseCodes to more detailed

src/App/ChatService.php, src/App/ContactusService.php, src/App/DailyFreeService.php, src/App/UserService.php, src/Database/ChatMapper.php
Change multiple response code according to provided information.
Affected files:
`src/App/ChatService.php`
`src/App/ContactusService.php`
`src/App/DailyFreeService.php`
`src/App/UserService.php`
`src/Database/ChatMapper.php`
=> feat(response code): update response code on services and ChatMapper

src/App/UserInfoService.php, src/App/UserService.php
Change Response message to Code in UserService.php and UserinfoService.php file
=> Change Response Code in UserService.php and UserinfoService.php file

src/App/McapService.php
It's done. @tasoraso please review it
=> Feat:Changed all response codes in McapService

src/App/ChatService.php
=> clean chatservice

src/App/UserService.php, src/Database/ChatMapper.php, src/Filter/PeerInputFilter.php
add new function to chatMapper to read message by id, and some responsecode ...
=> add new func to read message by id and more

src/App/ChatService.php
The ChatService finally finished and all response codes changed. @tasoraso please review it.
=> Feat:changed all response codes in ChatService

src/Database/PoolMapper.php, src/admin_schema.graphl, src/bridge_schema.graphl
Reduce the response of the solana bridge
=> Reduce the response of the solana bridge

src/Services/Mailer.php
=> Add Api Mailer To Services

composer.json
=> Remove phpmailer from composer.json

src/Middleware/RateLimiterMiddleware.php
=> fix rate limiter

src/Database/UserMapper.php, src/Database/WalletMapper.php
clean and improve UserMapper, WalletMapper
=> clean and tabtospace in mappers

src/Database/WalletMapper.php
=> Improve TransferToken

src/GraphQLSchemaBuilder.php
=> clean Builder Resolver

src/App/UserService.php, src/GraphQLSchemaBuilder.php
Register with email inluded token for verifiying.
=> register with email recieving with token verifiying

src/Services/Mailer.php
=> improve mailer with detailed log

src/App/ChatService.php, src/App/PostService.php, src/Database/WalletMapper.php, src/Filter/PeerInputFilter.php
Change multiple response code according to provided information.
=> feat(responseCode update): update severals code

src/schema.graphl
fixed a small error in the updated schema
=> fix(schema): fix error in schema.graphl

src/App/UserService.php
https://app.clickup.com/t/86c3bhf8r
=> fix(codes): Profile: 41007 to 21001

runtime-data/assets/response-codes-original.json, runtime-data/assets/response-codes.json, src/App/PostInfoService.php
Updated response codes for ResolvePostAction mutation (double share and code 21515 → 31504).
=> fix(response-codes): update ResolvePostAction codes and values

src/App/Comment.php, src/App/CommentService.php, src/Filter/PeerInputFilter.php
https://app.clickup.com/t/86c3c9pd1
=> feat(validaiton): passing exact errorCode field through string Inputfilter

src/Database/PoolMapper.php, src/GraphQLSchemaBuilder.php, src/admin_schema.graphl, src/schema.graphl
Updated the dailygemsresults query to include pkey (Solana wallet) and tokenAmount from users_info and wallett tables. @jakobPeer and @vidkazan please review it and give me feedback)
=> Update: added pkey to dailygemresuldata query

runtime-data/assets/response-codes.json
Sure, user-freindly messages should be reviewed, but later😅
=> feat(codes): update response codes file

sql_files_for_import/additional_data.sql
add first version of additional_data.sql file to the repo. 
it includes tester01 and tester02 and the burn, LP and company account. 
This needs to be updated with the release of the new transaction/swap functions!
=> feat(additional-data)

src/GraphQLSchemaBuilder.php
versions 8.3.21 or higher than that do not accept strlen getting a NULL. so i included the max check in the Null safe area.. should fix that
=> fix(strlength): 

runtime-data/assets/response-codes.json
Updating Response codes for resetPassword and requestPasswordReset API's.
=> feat(update response codes) : Updating reponse codes

.gitignore, src/App/PostService.php
Fix Deprecated strlen(): Passing null to parameter ($string) of type string is deprecated (php > 8.3.20)
query ListPosts {
listPosts {
status
counter
ResponseCode
}
}
PostService.php Line 432.
=> T ras/fix deprecated strlen

src/Database/UserMapper.php, src/Utils/DateService.php
Helping preparation changes https://app.clickup.com/t/86c3nv7up
=> feat(reset-password): requestsResetPassword: add nextAttemptAt timestamp

runtime-data/media/assets/config.json, runtime-data/media/assets/endpoints.json, runtime-data/media/assets/response-codes.json, src/config/backend-config-for-editing/response-codes-editable.json, tests/postman_collection/graphql_postman_collection.json
Added getActionPrice in the collection and assigned response codes.
=> Update : Response Codes, Postman Collection

src/App/WalletService.php, src/Database/WalletMapper.php, src/GraphQLSchemaBuilder.php, src/admin_schema.graphl, src/schema.graphl
Retrieve user transaction responses based on multiple filter criteria.
ClickUp: https://app.clickup.com/t/86c3aegp9
=> feat(get transaction list): get transaction history

src/Database/WalletMapper.php
Formating the number befor convert decimal to Q96
=> Fix Decimal 2 Q96

src/App/UserService.php, src/config/backend-config-for-editing/response-codes-editable.json, tests/postman_collection/graphql_postman_collection.json
Update: Referral Verification Tests and Response codes
=> Referral Verification

src/App/UserService.php, src/config/backend-config-for-editing/response-codes-editable.json, tests/postman_collection/graphql_postman_collection.json
Reverts peer-network/peer_backend#348
=> Revert "Referral Verification"

src/App/Chat.php, src/App/ChatMessages.php, src/App/ChatParticipantInfo.php, src/App/ChatParticipants.php, src/App/Comment.php, src/App/CommentAdvanced.php, src/App/CommentInfo.php, src/App/Commented.php, src/App/Contactus.php, src/App/DailyFree.php, src/App/Mcap.php, src/App/NewsFeed.php, src/App/Pool.php, src/App/Post.php, src/App/PostAdvanced.php, src/App/PostInfo.php, src/App/PostMedia.php, src/App/ProfilUser.php, src/App/Profile.php, src/App/Tag.php, src/App/TagPost.php, src/App/Tokenize.php, src/App/User.php, src/App/UserAdvanced.php, src/App/UserBlock.php, src/App/UserInfo.php, src/App/Wallet.php, src/App/Wallett.php
fixed function return type in entities validation functions
=> fix(entity-validation): change function return type

src/GraphQLSchemaBuilder.php, src/admin_schema.graphl, src/schema.graphl
Fixed naming in graphQL schema
=> fix(gql): fix gql-schema

Dockerfile
reverted the composer install command in dockerfile
=> fixed Docker compose install run command

sql_files_for_import/20250723000000_transactions_table.sql, src/App/Models/Transaction.php, src/App/PeerTokenService.php, src/Database/PeerTokenMapper.php, src/GraphQLSchemaBuilder.php, src/admin_schema.graphl, src/config/constants/ConstantsConfig.php, src/schema.graphl
Get Transaction History out of token-transfer Branch.
ClickUp: [https://app.clickup.com/t/86c4n95gf](https://app.clickup.com/t/86c4n95gf?utm_source=email-notifications&utm_type=1&utm_field=assignee_add)
=> feat(Extract transaction history): Get Transaction history scripts from transfer token

Dockerfile
=> added rust and Cargo.toml

.github/workflows/Newman_backend_test.yaml, src/Services/Base64FileHandler.php
- Removed webm file extension from whitelist, see: https://app.clickup.com/t/86c4nth83
- CI Pipeline: Restored sql checks
=> fix(file-handler): remove webm

src/App/PostService.php, src/Database/WalletMapper.php
- multipart/form-data - fixed tmp files expiry
- rust calculations usage for minting
=> 🟡 hotfixes to pre-release

.github/dependabot.yml, .github/workflows/dependabot-alerts.yml, Dockerfile.newman, docker-compose.override.local.yml, sql_files_for_import/20250827000000_tokenamount_change.sql, src/App/Models/Transaction.php, src/App/Repositories/TransactionRepository.php, src/Database/PeerTokenMapper.php, src/GraphQLSchemaBuilder.php, src/admin_schema.graphl, src/schema.graphl, tests/postman_collection/001_graphql_postman_collection.json, tests/postman_collection/002_graphql_postman_collection.json, tests/postman_collection/003_graphql_postman_collection.json
=> 🟡 merge dev hot-fixes to staging

.github/workflows/Newman_backend_test.yaml
Added retry login logic to GHCR login step just if some network delays
=> Added retry login login to GHCR

.github/workflows/Newman_backend_test.yaml
changed to the latest artifact upload version v5 so trivy upload can pass, and removed duplicate step that performs same operation in trivy
=> changed upload artifact version to v5

.github/workflows/dependabot-update-alerts.yml
added actions checkout. and also if clause for label.
=> added actions checkout. and also if clause for label.

Makefile
modified compose project name to match upper and lower case letters
=> modified compose project name to match upper and lower case letters

src/config/backend-config-for-editing/endpoints-editable.json
upsi pupsi someone (*cough*) just did it on the server and not in git .... 👼🏼
=> conf(versions): update versions in git so that the servers are not reverted on update
